[package]
name = "test-dapp"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.8.1"

[features]
test-bpf = []

[dev-dependencies]
assert_matches = "1.4.0"
solana-program-test = "=1.8.1"
solana-sdk = "=1.8.1"
solana-validator = "=1.8.1"

[lib]
crate-type = ["cdylib", "lib"]
